// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Workbalance.Infrastructure.Context;

#nullable disable

namespace Workbalance.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workbalance.Domain.Entity.MoodEntry", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CD_MOOD_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(0)")
                        .HasColumnName("TS_CREATED_AT");

                    b.Property<DateTime>("Date")
                        .HasColumnType("DATE")
                        .HasColumnName("DT_DATE");

                    b.Property<byte>("Mood")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("NR_MOOD");

                    b.Property<string>("Notes")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DS_NOTES");

                    b.Property<byte>("Productivity")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("NR_PRODUCTIVITY");

                    b.Property<byte>("Stress")
                        .HasColumnType("NUMBER(3)")
                        .HasColumnName("NR_STRESS");

                    b.Property<string>("Tags")
                        .HasColumnType("VARCHAR2(500)")
                        .HasColumnName("DS_TAGS");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP(0)")
                        .HasColumnName("TS_UPDATED_AT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CD_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Date")
                        .IsUnique()
                        .HasDatabaseName("UQ_WB_MOOD_USER_DATE");

                    b.ToTable("WB_MOOD_ENTRY", (string)null);
                });

            modelBuilder.Entity("Workbalance.Domain.Entity.Recommendation", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CD_RECOMMENDATION_ID");

                    b.Property<string>("ActionUrl")
                        .HasColumnType("VARCHAR2(300)")
                        .HasColumnName("DS_ACTION_URL");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP(0)")
                        .HasColumnName("TS_CREATED_AT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(200)")
                        .HasColumnName("DS_MESSAGE");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("TIMESTAMP(0)")
                        .HasColumnName("TS_SCHEDULED_AT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DS_SOURCE");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(20)")
                        .HasColumnName("DS_TYPE");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CD_USER_ID");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("IDX_WB_RECOM_USER_CREATED");

                    b.ToTable("WB_RECOMMENDATION", (string)null);
                });

            modelBuilder.Entity("Workbalance.Domain.Entity.User", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("VARCHAR2(36)")
                        .HasColumnName("CD_USER_ID");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TS_CREATED_AT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("NVARCHAR2(120)")
                        .HasColumnName("DS_EMAIL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("NVARCHAR2(80)")
                        .HasColumnName("NM_NAME");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("NVARCHAR2(255)")
                        .HasColumnName("DS_PASSWORD_HASH");

                    b.Property<string>("PreferredLanguage")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("DS_PREFERRED_LANGUAGE")
                        .HasDefaultValueSql("'pt-BR'");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TIMESTAMP")
                        .HasColumnName("TS_UPDATED_AT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("WB_USER", (string)null);
                });

            modelBuilder.Entity("Workbalance.Domain.Entity.MoodEntry", b =>
                {
                    b.HasOne("Workbalance.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Workbalance.Domain.Entity.Recommendation", b =>
                {
                    b.HasOne("Workbalance.Domain.Entity.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
